name: JOPHCraft
main: me.jophestus.JOPHCraft.JOPHCraft
version: 2.1
description: Custom recepie plugin for Black Minor!
commands:
    JOPHCraft:
        description: Lists JOPHCraft version
    jchelp:
        description: Displayes JOPHCraft Help